address: ":6381"
grpc_address: "localhost:50053"
log_path: "./tmp/log3"
data_path: "./tmp/storage3"
bootstrap_servers: ["localhost:50051", "localhost:50052", "localhost:50053"]
write_pref: "all"
read_pref: "all"
timeout: 1000000000
