// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: proto/startup.proto

package startup

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StartupServiceClient is the client API for StartupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StartupServiceClient interface {
	GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error)
}

type startupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStartupServiceClient(cc grpc.ClientConnInterface) StartupServiceClient {
	return &startupServiceClient{cc}
}

func (c *startupServiceClient) GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error) {
	out := new(GetNodeInfoResponse)
	err := c.cc.Invoke(ctx, "/kvbridge.StartupService/GetNodeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StartupServiceServer is the server API for StartupService service.
// All implementations must embed UnimplementedStartupServiceServer
// for forward compatibility
type StartupServiceServer interface {
	GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error)
	mustEmbedUnimplementedStartupServiceServer()
}

// UnimplementedStartupServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStartupServiceServer struct {
}

func (UnimplementedStartupServiceServer) GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (UnimplementedStartupServiceServer) mustEmbedUnimplementedStartupServiceServer() {}

// UnsafeStartupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StartupServiceServer will
// result in compilation errors.
type UnsafeStartupServiceServer interface {
	mustEmbedUnimplementedStartupServiceServer()
}

func RegisterStartupServiceServer(s grpc.ServiceRegistrar, srv StartupServiceServer) {
	s.RegisterService(&StartupService_ServiceDesc, srv)
}

func _StartupService_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StartupServiceServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvbridge.StartupService/GetNodeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StartupServiceServer).GetNodeInfo(ctx, req.(*GetNodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StartupService_ServiceDesc is the grpc.ServiceDesc for StartupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StartupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kvbridge.StartupService",
	HandlerType: (*StartupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeInfo",
			Handler:    _StartupService_GetNodeInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/startup.proto",
}
